// <auto-generated />
using System;
using Hotelix.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotelix.API.Data.Migrations
{
    [DbContext(typeof(HotelixAPIContext))]
    partial class HotelixAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotelix.API.Data.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6201),
                            HotelId = 1,
                            HouseNumber = 10,
                            PostalCode = "43-382",
                            SoftDeleted = false,
                            Street = "Tańskiego",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6203)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6211),
                            HotelId = 2,
                            HouseNumber = 12,
                            PostalCode = "43-345",
                            SoftDeleted = false,
                            Street = "Słowackiego",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6212)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6215),
                            HotelId = 3,
                            HouseNumber = 1,
                            PostalCode = "31-436",
                            SoftDeleted = false,
                            Street = "Wojska polskiego",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6216)
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6218),
                            HotelId = 4,
                            HouseNumber = 24,
                            PostalCode = "31-450",
                            SoftDeleted = false,
                            Street = "Powstańców",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6219)
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6221),
                            HotelId = 5,
                            HouseNumber = 34,
                            PostalCode = "40-102",
                            SoftDeleted = false,
                            Street = "Węglowa",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6223)
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6226),
                            HotelId = 6,
                            HouseNumber = 4,
                            PostalCode = "40-304",
                            SoftDeleted = false,
                            Street = "Kopalniana",
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6228)
                        });
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6015),
                            Name = "Bielsko-Biała",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6059)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6066),
                            Name = "Kraków",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6068)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6070),
                            Name = "Katowice",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6071)
                        });
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6254),
                            Email = "prezydent@hotelix.pl",
                            HotelId = 1,
                            PhoneNumber = "123 456 789",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6256)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6260),
                            HotelId = 2,
                            PhoneNumber = "123 456 789",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6261)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6263),
                            Email = "kierownik@hotelix.pl",
                            HotelId = 3,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6264)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6266),
                            Email = "praktykant@hotelix.pl",
                            HotelId = 4,
                            PhoneNumber = "123 456 789",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6267)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6269),
                            HotelId = 5,
                            PhoneNumber = "123 456 789",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6270)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6273),
                            Email = "senior@hotelix.pl",
                            HotelId = 6,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6274)
                        });
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.HotelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCafeteria")
                        .HasColumnType("bit");

                    b.Property<bool>("HasInternet")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTelevision")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6114),
                            Description = "Lorem Ipsum",
                            HasCafeteria = false,
                            HasInternet = true,
                            HasParking = true,
                            HasTelevision = false,
                            Name = "Hotel Prezydent",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6116)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6122),
                            HasCafeteria = false,
                            HasInternet = false,
                            HasParking = false,
                            HasTelevision = true,
                            Name = "Hotel Prezes",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6123)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6125),
                            Description = "Lorem Ipsum",
                            HasCafeteria = true,
                            HasInternet = false,
                            HasParking = true,
                            HasTelevision = false,
                            Name = "Hotel Kierownik",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6126)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6129),
                            HasCafeteria = false,
                            HasInternet = false,
                            HasParking = false,
                            HasTelevision = false,
                            Name = "Hotel Praktykant",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6131)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6132),
                            Description = "Lorem Ipsum",
                            HasCafeteria = false,
                            HasInternet = false,
                            HasParking = false,
                            HasTelevision = false,
                            Name = "Hotel Stażysta",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6134)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6137),
                            HasCafeteria = false,
                            HasInternet = true,
                            HasParking = false,
                            HasTelevision = false,
                            Name = "Hotel Senior",
                            PricePerNight = 0m,
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6138)
                        });
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6302),
                            Password = "fikunia123",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6304),
                            UserName = "FilipMadzia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6306),
                            Password = "kochamBobry",
                            SoftDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 11, 14, 27, 12, 984, DateTimeKind.Local).AddTicks(6308),
                            UserName = "WojtekWróbel"
                        });
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.AddressEntity", b =>
                {
                    b.HasOne("Hotelix.API.Data.Entities.CityEntity", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotelix.API.Data.Entities.HotelEntity", "Hotel")
                        .WithOne("Address")
                        .HasForeignKey("Hotelix.API.Data.Entities.AddressEntity", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.ContactEntity", b =>
                {
                    b.HasOne("Hotelix.API.Data.Entities.HotelEntity", "Hotel")
                        .WithOne("Contact")
                        .HasForeignKey("Hotelix.API.Data.Entities.ContactEntity", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.CityEntity", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Hotelix.API.Data.Entities.HotelEntity", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
