@Hotelix.API_HostAddress = http://localhost:5000/api

GET {{Hotelix.API_HostAddress}}/Cities
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Cities/1
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Addresses
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Addresses/1
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Contacts
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Contacts/1
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Hotels
Accept: application/json

###

GET {{Hotelix.API_HostAddress}}/Hotels/1
Accept: application/json

###
